- name: Install MongoDB
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Define variables for replication config on primary node
      set_fact:
        # for replica set init only
        mongodb_master: true
        mongodb_login_host: "{{ IP_ADDRESS }}"
        mongodb_replication_params:
          - {
              host_name: "{{ IP_ADDRESS }}",
              host_port: "{{ MONGODB_PORT }}",
              host_type: replica,
            }
        mongodb_replication_oplogsize: "{{ MONGODB_REPLICATION_OPLOGSIZE }}"
      when: (mongodb_replication_replset is defined) and (mongodb_replication_replset|length > 0)
    - name: Set key file content
      set_fact:
        mongodb_keyfile_content: "{{ MONGODB_KEYFILE_CONTENT }}"
      when: (MONGODB_KEYFILE_CONTENT is defined) and (MONGODB_KEYFILE_CONTENT|length > 0)
      no_log: true
    - name: Install MongoDB using role ansible-role-mongodb from UnderGreen
      import_role:
        name: undergreen.ansible-role-mongodb
      vars:
        mongodb_version: "{{ MONGODB_VERSION }}"
        mongodb_net_bindip: "{{ IP_ADDRESS }},127.0.0.1"
        mongodb_net_port: "{{ MONGODB_PORT }}"
        mongodb_storage_dbpath: "{{ MONGODB_DB_PATH }}"
        mongodb_disable_transparent_hugepages: "{{ MONGODB_DISABLE_TRANSPARENT_HUGEPAGES }}"
        mongodb_use_numa: "{{ MONGODB_USE_NUMA }}"
        mongodb_net_ipv6: "{{ MONGODB_NET_IPV6 }}"
        mongodb_net_maxconns: "{{ MONGODB_NET_MAXCONNS }}"
        mongodb_net_http_enabled: "{{ MONGODB_NET_HTTP_ENABLED }}"
        mongodb_storage_quota_enforced: "{{ MONGODB_STORAGE_QUOTA_ENFORCED }}"
        mongodb_storage_quota_maxfiles: "{{ MONGODB_STORAGE_QUOTA_MAXFILES }}"
        mongodb_storage_smallfiles: "{{ MONGODB_STORAGE_SMALLFILES }}"
        mongodb_storage_journal_enabled: "{{ MONGODB_STORAGE_JOURNAL_ENABLED }}"
        mongodb_storage_prealloc: "{{ MONGODB_STORAGE_PREALLOC }}"
        mongodb_wiredtiger_cache_size: "{{ MONGODB_WIREDTIGER_CACHE_SIZE }}"
        mongodb_security_authorization: "{{ MONGODB_SECURITY_AUTHORIZATION }}"
        mongodb_users: "{{ MONGODB_USERS }}"
        mongodb_user_admin_name: "{{ MONGODB_USER_ADMIN_NAME }}"
        mongodb_user_admin_password: "{{ MONGODB_USER_ADMIN_PASSWORD }}"
        mongodb_root_admin_name: "{{ MONGODB_ROOT_ADMIN_NAME }}"
        mongodb_root_admin_password: "{{ MONGODB_ROOT_ADMIN_PASSWORD }}"
        mongodb_root_backup_name: "{{ MONGODB_ROOT_BACKUP_NAME }}"
        mongodb_root_backup_password: "{{ MONGODB_ROOT_BACKUP_PASSWORD }}"
        mongodb_replication_replset: "{{ MONGODB_REPLICATION_REPLSET }}"