- name: Install node exporter
  hosts: all
  become: true
  tasks:
    - name: Create alertmanager
      import_role:
        name: alertmanager
      vars:
        alertmanager_version: "{{ VERSION }}"
        alertmanager_web_listen_address: "{{ IP_ADDRESS }}:{{ PORT }}"
        alertmanager_config_dir: "{{ CONFIG_DIR }}"
        alertmanager_db_dir: "{{ DB_DIR }}"
        alertmanager_resolve_timeout: "{{ RESOLVE_TIMEOUT }}"
        alertmanager_route: "{{ ROUTE }}"
        alertmanager_receivers: "{{ RECEIVERS }}"
        alertmanager_http_config: "{{ HTTP_CONFIG | default({}, true) }}"