- name: Download openshift-client
  get_url:
    url: "https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/4.16.19/openshift-client-linux.tar.gz"
    dest: "{{ openshift_dir }}/openshift-client-linux.tar.gz"
    mode: 0640
- name: Unarchive openshift-client
  become: true
  unarchive:
    src: "{{ openshift_dir }}/openshift-client-linux.tar.gz"
    dest: /usr/bin
    remote_src: yes