- name: Install openlitespeed, php, mysql, and wordpress
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  vars:
    owner: www-data
    group: www-data
    #PHP Settings
    php_version: "74"
    php_dversion: "7.4"
    php_opt_modules: 
      - "curl"
      - "imagick"
      - "intl"
      - "opcache"
      - "memcached"
      - "tidy"
    wordpress_version: "{{ WORDPRESS_VERSION }}"
    php_memory_limit: "{{ PHP_MEMORY_LIMIT }}"
    php_max_execution_time: "60"
    php_upload_max_filesize: "{{ PHP_UPLOAD_MAX_FILESIZE }}"
    php_post_max_size: "{{ PHP_POST_MAX_SIZE }}"
    #MySQL Settings
    mysql_host: "{{ MYSQL_HOST }}"
    mysql_db: "{{ MYSQL_DB }}"
    mysql_encoding: "{{ MYSQL_ENCODING }}"
    mysql_user: "{{ MYSQL_USER }}"
    mysql_password: "{{ MYSQL_PASSWORD }}"
    #HTTP Settings
    http_host: "wordpress"
    http_port: "80"
    https_port: "{{ HTTPS_PORT }}"
    doc_root: "/var/www/wordpress"
    ssl_key: "{{ SSL_KEY }}"
    ssl_crt: "{{ SSL_CRT }}"
  tasks:
    - name: Install openlitespeed
      import_role:
        name: 'roles/openlitespeed_wordpress/roles/openlitespeed'
    - name: Install php
      import_role:
        name: 'roles/openlitespeed_wordpress/roles/php'
    # - name: Install mysql
    #   import_role:
    #     name: 'roles/openlitespeed_wordpress/roles/mysql'
    - name: Install wordpress
      import_role:
        name: 'openlitespeed_wordpress/roles/wordpress'