- name: Install OS hardening
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Import ansible role os hardening
      import_role:
        name: 'ansible-collection-hardening/roles/os_hardening'
      vars:
        os_desktop_enable: "{{ OS_DESKTOP_ENABLE }}"
        os_env_extra_user_paths: "{{ OS_ENV_EXTRA_USER_PATHS }}"
        os_env_umask: "{{ OS_ENV_UMASK }}"
        os_auth_pw_max_age: "{{ OS_AUTH_PW_MAX_AGE }}"
        os_auth_pw_min_age: "{{ OS_AUTH_PW_MIN_AGE }}"
        os_auth_pw_remember: "{{ OS_AUTH_PW_REMEMBER }}"
        # os_auth_retries: "{{ OS_AUTH_RETRIES }}" not support for now. Default to 5 in os_hardening role.
        os_auth_lockout_time: "{{ OS_AUTH_LOCKOUT_TIME }}"
        os_auth_timeout: "{{ OS_AUTH_TIMEOUT }}"
        os_auth_allow_homeless: "{{ OS_AUTH_ALLOW_HOMELESS }}"
        os_auth_pam_passwdqc_enable: "{{ OS_AUTH_PAM_PASSWDQC_ENABLE }}"
        os_auth_pam_passwdqc_options: "{{ OS_AUTH_PAM_PASSWDQC_OPTIONS }}"
        os_auth_pam_sssd_enable: "{{ OS_AUTH_PAM_SSSD_ENABLE }}"
        os_security_users_allow: "{{ OS_SECURITY_USERS_ALLOW }}"
        os_security_kernel_enable_module_loading: "{{ OS_SECURITY_KERNEL_ENABLE_MODULE_LOADING }}"
        os_security_kernel_enable_core_dump: "{{ OS_SECURITY_KERNEL_ENABLE_CORE_DUMP }}"
        os_security_suid_sgid_enforce: "{{ OS_SECURITY_SUID_SGID_ENFORCE }}"
        os_security_suid_sgid_blacklist: "{{ OS_SECURITY_SUID_SGID_BLACKLIST }}"
        os_security_suid_sgid_whitelist: "{{ OS_SECURITY_SUID_SGID_WHITELIST }}"
        os_security_suid_sgid_remove_from_unknown: "{{ OS_SECURITY_SUID_SGID_REMOVE_FROM_UNKNOWN }}"
        os_auth_uid_min: "{{ OS_AUTH_UID_MIN }}"
        os_auth_uid_max: "{{ OS_AUTH_UID_MAX }}"
        os_auth_gid_min: "{{ OS_AUTH_GID_MIN }}"
        os_auth_gid_max: "{{ OS_AUTH_GID_MAX }}"
        os_auth_sub_uid_count: "{{ OS_AUTH_SUB_UID_COUNT }}"
        os_auth_sub_uid_min: "{{ OS_AUTH_SUB_UID_MIN }}"
        os_auth_sub_uid_max: "{{ OS_AUTH_SUB_UID_MAX }}"
        os_auth_sub_gid_count: "{{ OS_AUTH_SUB_GID_COUNT }}"
        os_auth_sub_gid_min: "{{ OS_AUTH_SUB_GID_MIN }}"
        os_auth_sub_gid_max: "{{ OS_AUTH_SUB_GID_MAX }}"
        os_security_packages_clean: "{{ OS_SECURITY_PACKAGES_CLEAN }}"
        os_selinux_state: "{{ OS_SELINUX_STATE }}"
        os_selinux_policy: "{{ OS_SELINUX_POLICY }}"
        ufw_manage_defaults: "{{ UFW_MANAGE_DEFAULTS }}"
        ufw_ipt_sysctl: "{{ UFW_IPT_SYSCTL }}"
        ufw_default_input_policy: "{{ UFW_DEFAULT_INPUT_POLICY }}"
        ufw_default_output_policy: "{{ UFW_DEFAULT_OUTPUT_POLICY }}"
        ufw_default_forward_policy: "{{ UFW_DEFAULT_FORWARD_POLICY }}"
        ufw_enable_ipv6: "{{ UFW_ENABLE_IPV6 }}"
        os_auditd_enabled: "{{ OS_AUDITD_ENABLED }}"
        os_auditd_max_log_file_action: "{{ OS_AUDITD_MAX_LOG_FILE_ACTION }}"
        os_auditd_max_log_file: "{{ OS_AUDITD_MAX_LOG_FILE }}"
        hidepid_option: "{{ HIDEPID_OPTION }}"
        proc_mnt_options: "{{ PROC_MNT_OPTIONS }}"
        os_ignore_home_folder_users: "{{ OS_IGNORE_HOME_FOLDER_USERS }}"
        os_cron_enabled: "{{ OS_CRON_ENABLED }}"
        os_limits_enabled: "{{ OS_LIMITS_ENABLED }}"
        os_login_defs_enabled: "{{ OS_LOGIN_DEFS_ENABLED }}"
        os_minimize_access_enabled: "{{ OS_MINIMIZE_ACCESS_ENABLED }}"
        os_pam_enabled: "{{ OS_PAM_ENABLED }}"
        os_modprobe_enabled: "{{ OS_MODPROBE_ENABLED }}"
        os_profile_enabled: "{{ OS_PROFILE_ENABLED }}"
        os_securetty_enabled: "{{ OS_SECURETTY_ENABLED }}"
        os_sysctl_enabled: "{{ OS_SYSCTL_ENABLED }}"
        os_user_accounts_enabled: "{{ OS_USER_ACCOUNTS_ENABLED }}"
        os_rhosts_enabled: "{{ OS_RHOSTS_ENABLED }}"
        os_yum_enabled: "{{ OS_YUM_ENABLED }}"
        os_apt_enabled: "{{ OS_APT_ENABLED }}"
        os_selinux_enabled: "{{ OS_SELINUX_ENABLED }}"
        os_sha_crypt_min_rounds: "{{ OS_SHA_CRYPT_MIN_ROUNDS }}"
        os_sha_crypt_max_rounds: "{{ OS_SHA_CRYPT_MAX_ROUNDS }}"