- name: Install OS hardening
  hosts: all
  strategy: free
  become: true
  become_method: sudo
  tasks:
    - name: Import ansible role os hardening
      import_role:
        name: 'ansible-collection-hardening/roles/ssh_hardening'
      vars:
        network_ipv6_enable: "{{ NETWORK_IPV6_ENABLE }}"
        ssh_client_config_file: "{{ SSH_CLIENT_CONFIG_FILE }}"
        ssh_server_config_file: "{{ SSH_SERVER_CONFIG_FILE }}"
        ssh_client_port: "{{ SSH_CLIENT_PORT }}"
        ssh_listen_to: "{{ SSH_LISTEN_TO }}"
        ssh_host_key_files: "{{ SSH_HOST_KEY_FILES }}"
        ssh_host_rsa_key_size: "{{ SSH_HOST_RSA_KEY_SIZE }}"
        ssh_host_key_algorithms: "{{ SSH_HOST_KEY_ALGORITHMS }}"
        ssh_client_host_key_algorithms: "{{ SSH_CLIENT_HOST_KEY_ALGORITHMS }}"
        ssh_client_alive_interval: "{{ SSH_CLIENT_ALIVE_INTERVAL }}"
        ssh_client_alive_count: "{{ SSH_CLIENT_ALIVE_COUNT }}"
        ssh_permit_tunnel: "{{ SSH_PERMIT_TUNNEL }}"
        ssh_remote_hosts: "{{ SSH_REMOTE_HOSTS }}"
        ssh_permit_root_login: "{{ SSH_PERMIT_ROOT_LOGIN }}"
        ssh_allow_tcp_forwarding: "{{ SSH_ALLOW_TCP_FORWARDING }}"
        ssh_gateway_ports: "{{ SSH_GATEWAY_PORTS }}"
        ssh_allow_agent_forwarding: "{{ SSH_ALLOW_AGENT_FORWARDING }}"
        ssh_x11_forwarding: "{{ SSH_X11_FORWARDING }}"
        ssh_pam_support: "{{ SSH_PAM_SUPPORT }}"
        ssh_use_pam: "{{ SSH_USE_PAM }}"
        ssh_gssapi_support: "{{ SSH_GSSAPI_SUPPORT }}"
        ssh_gssapi_delegation: "{{ SSH_GSSAPI_DELEGATION }}"
        ssh_kerberos_support: "{{ SSH_KERBEROS_SUPPORT }}"
        ssh_deny_users: "{{ SSH_DENY_USERS }}"
        ssh_allow_users: "{{ SSH_ALLOW_USERS }}"
        ssh_deny_groups: "{{ SSH_DENY_GROUPS }}"
        ssh_allow_groups: "{{ SSH_ALLOW_GROUPS }}"
        ssh_authorized_keys_file: "{{ SSH_AUTHORIZED_KEYS_FILE }}"
        ssh_trusted_user_ca_keys_file: "{{ SSH_TRUSTED_USER_CA_KEYS_FILE }}"
        ssh_trusted_user_ca_keys: "{{ SSH_TRUSTED_USER_CA_KEYS }}"
        ssh_authorized_principals_file: "{{ SSH_AUTHORIZED_PRINCIPALS_FILE }}"
        ssh_authorized_principals: "{{ SSH_AUTHORIZED_PRINCIPALS }}"
        ssh_print_motd: "{{ SSH_PRINT_MOTD }}"
        ssh_print_pam_motd: "{{ SSH_PRINT_PAM_MOTD }}"
        ssh_print_last_log: "{{ SSH_PRINT_LAST_LOG }}"
        sftp_enabled: "{{ SFTP_ENABLED }}"
        sftp_umask: "{{ SFTP_UMASK }}"
        sftp_chroot: "{{ SFTP_CHROOT }}"
        sftp_chroot_dir: "{{ SFTP_CHROOT_DIR }}"
        ssh_client_roaming: "{{ SSH_CLIENT_ROAMING }}"
        sshd_moduli_file: "{{ SSHD_MODULI_FILE }}"
        sshd_moduli_minimum: "{{ SSHD_MODULI_MINIMUM }}"
        ssh_challengeresponseauthentication: "{{ SSH_CHALLENGERESPONSEAUTHENTICATION }}"
        ssh_client_password_login: "{{ SSH_CLIENT_PASSWORD_LOGIN }}"
        ssh_banner: "{{ SSH_BANNER }}"
        ssh_banner_path: "{{ SSH_BANNER_PATH }}"
        ssh_client_hardening: "{{ SSH_CLIENT_HARDENING }}"
        ssh_client_compression: "{{ SSH_CLIENT_COMPRESSION }}"
        ssh_compression: "{{ SSH_COMPRESSION }}"
        ssh_login_grace_time: "{{ SSH_LOGIN_GRACE_TIME }}"
        ssh_max_auth_retries: "{{ SSH_MAX_AUTH_RETRIES }}"
        ssh_max_sessions: "{{ SSH_MAX_SESSIONS }}"
        ssh_print_debian_banner: "{{ SSH_PRINT_DEBIAN_BANNER }}"
        ssh_server_enabled: "{{ SSH_SERVER_ENABLED }}"
        ssh_server_hardening: "{{ SSH_SERVER_HARDENING }}"
        ssh_server_match_address: "{{ SSH_SERVER_MATCH_ADDRESS }}"
        ssh_server_match_group: "{{ SSH_SERVER_MATCH_GROUP }}"
        ssh_server_match_user: "{{ SSH_SERVER_MATCH_USER }}"
        ssh_server_match_local_port: "{{ SSH_SERVER_MATCH_LOCAL_PORT }}"
        ssh_server_permit_environment_vars: "{{ SSH_SERVER_PERMIT_ENVIRONMENT_VARS }}"
        ssh_server_accept_env_vars: "{{ SSH_SERVER_ACCEPT_ENV_VARS }}"
        ssh_use_dns: "{{ SSH_USE_DNS }}"
        ssh_server_revoked_keys: "{{ SSH_SERVER_REVOKED_KEYS }}"
        ssh_max_startups: "{{ SSH_MAX_STARTUPS }}"
        ssh_macs: "{{ SSH_MACS }}"
        ssh_kex: "{{ SSH_KEX }}"
        ssh_ciphers: "{{ SSH_CIPHERS }}"
        ssh_custom_options: "{{ SSH_CUSTOM_OPTIONS }}"
        sshd_custom_options: "{{ SSHD_CUSTOM_OPTIONS }}"
        sshd_syslog_facility: "{{ SSHD_SYSLOG_FACILITY }}"
        sshd_log_level: "{{ SSHD_LOG_LEVEL }}"
        sshd_strict_modes: "{{ SSHD_STRICT_MODES }}"
        sshd_authenticationmethods: "{{ SSHD_AUTHENTICATIONMETHODS }}"