# Copyright (C) 2022 Open Telekom Cloud - T-Systems International GmbH.
# Use of this source code is governed by Apache 2 LICENSE that can be found in the LICENSE file.
- name: Create MySQL database and user
  hosts: all
  strategy: free
  gather_facts: no
  tasks:
    - name: Create MySQL database
      become: true
      mysql_db:
        name: "{{ MYSQL_DB }}"
        collation: "{{ MYSQL_COLLATION }}"
        encoding: "{{ MYSQL_ENCODING }}"
        login_user: root
        login_password: "{{ MYSQL_ROOT_PASSWORD }}"
        state: present
    - name: Create MySQL user
      become: true
      mysql_user:
        name: "{{ MYSQL_USER }}"
        password: "{{ MYSQL_PASSWORD }}"
        host: '%'
        priv: "{{ MYSQL_DB }}.*:ALL"
        state: present
        login_user: root
        login_password: "{{ MYSQL_ROOT_PASSWORD }}"